# Account for the operator itself. It should require namespace scoped
# permissions.
kind: ServiceAccount
apiVersion: v1
metadata:
  name: cluster-dns-operator
  namespace: openshift-cluster-dns-operator
